---
- hosts: elastic_cluster
  become: true
  gather_facts: false
  tasks:
    - name: Wait for /var/lib/dpkg/lock-frontend to be released 
      shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;
    - name: Install 8.12 version of Elasticsearch
      apt:
        name: elasticsearch=8.12.0
        state: present
        update_cache: yes

    - name: Reload systemd after changing unit files
      systemd:
        daemon_reload: yes
      become: yes

    - name: Enable Elasticsearch service
      systemd:
        name: elasticsearch
        enabled: yes
      become: yes

- name: Configure Elasticsearch
  hosts: elastic_master:elastic_hotnodes:elastic_coldnodes:elastic_misc
  become: yes
  gather_facts: false
  become_user: root
  tasks:
    - template:
        src: ../templates/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
      vars:
        node_roles: |
          {% if 'elastic_hotnodes' in group_names %}
            ["data_warm", "data_hot", "data_content"]
          {% elif 'elastic_coldnodes' in group_names %}
            ["data_cold", "data_frozen"]
          {% elif 'elastic_misc' in group_names %}
            ["ingest", "ml", "remote_cluster_client", "transform"]
          {% else %}
            ["master"]
          {% endif %}

        seed_hosts: "{{ groups['elastic_master'] | map('extract', hostvars, 'inventory_hostname') | list }}"
        initial_master_nodes: "{{ groups['elastic_master'] | map('extract', hostvars, 'inventory_hostname') | list }}"

