---
- name: Copy SSL Certificates to Remote Hosts
  hosts: elastic_cluster
  gather_facts: false
  become: true  

  tasks:
    - name: Copy privkey.pem
      copy:
        src: ../certs/privkey.pem 
        dest: /etc/elasticsearch/certs/privkey.pem  
        mode: '0660' 

    - name: Copy fullchain.pem
      copy:
        src: ../certs/fullchain.pem 
        dest: /etc/elasticsearch/certs/fullchain.pem 
        mode: '0664' 

    - name: Change ownership of privkey.pem
      ansible.builtin.file:
        path: /etc/elasticsearch/certs/privkey.pem
        owner: root
        group: elasticsearch

    - name: Change ownership of fullchain.pem
      ansible.builtin.file:
        path: /etc/elasticsearch/certs/fullchain.pem
        owner: root
        group: elasticsearch

- name: Copy SSL Certificates to Remote Hosts
  hosts: kibana_hosts
  gather_facts: false
  become: true  

  tasks:
    - name: Create /etc/kibana/certs directory
      ansible.builtin.file:
        path: /etc/kibana/certs
        state: directory
        mode: '0755'
        owner: root
        group: kibana
    - name: Copy privkey.pem
      copy:
        src: ../certs/privkey.pem  
        dest: /etc/kibana/certs/privkey.pem  
        mode: '0660'  

    - name: Copy fullchain.pem
      copy:
        src: ../certs/fullchain.pem  
        dest: /etc/kibana/certs/fullchain.pem  
        mode: '0664'  

    - name: Change ownership of privkey.pem
      ansible.builtin.file:
        path: /etc/kibana/certs/privkey.pem
        owner: root
        group: kibana

    - name: Change ownership of fullchain.pem
      ansible.builtin.file:
        path: /etc/kibana/certs/fullchain.pem
        owner: root
        group: kibana

- name: Enable and Start Elasticsearch service
  hosts: elastic_cluster 
  become: true

  tasks:
    - name: Enable and start Elasticsearch service
      ansible.builtin.systemd:
        name: elasticsearch
        state: started
        enabled: yes

- name: Execute Elasticsearch Password Reset Script
  hosts: "{{ hostvars[groups['elastic_master'][0]].inventory_hostname }}"
  become: true
  vars_files:
    - ../vault.yml
  tasks:
    - name: Execute password reset script for elastic user
      ansible.builtin.shell:
        cmd: "/usr/bin/printf '{{ elasticsearch_password }}\n{{ elasticsearch_password }}\n' | /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -i -f -b -s --url https://{{ hostvars[groups['elastic_master'][0]].inventory_hostname }}:9200"
    - name: Execute password reset script for kibana_system user
      ansible.builtin.shell:
        cmd: "/usr/bin/printf '{{ kibana_system_password }}\n{{ kibana_system_password }}\n' | /usr/share/elasticsearch/bin/elasticsearch-reset-password -u kibana_system -i -f -b -s --url https://{{ hostvars[groups['elastic_master'][0]].inventory_hostname }}:9200"

- name: Enable and Start Kibana service
  hosts: kibana_hosts 
  become: true

  tasks:
    - name: Enable and start Kibana service
      ansible.builtin.systemd:
        name: kibana
        state: started
        enabled: yes

