---
- name: Uninstall and Clean Up Elasticsearch
  hosts: elastic_cluster
  become: yes

  tasks:
    - name: Purge Elasticsearch Package
      ansible.builtin.apt:
        name: elasticsearch
        state: absent

